package src.src.com.company;

import java.util.ArrayList;
import java.util.List;

public abstract class Client extends Person {
	private static int clientId = 1000;

	private List<Experience> experiences;
	private List<Client> group;
	private double commission;
	private List<Award> awards;
	private int id;
	private double annualRevenueGenerated;

	public Client(String name, int age, String gender, String nationality,
			List<Experience> experiences, double commission, List<Award> awards, double annualRevenueGenerated) {
		super(name, age, gender, nationality);
		
		this.experiences = experiences;
		this.group = new ArrayList<Client>();
		this.commission = commission;
		this.awards = awards;
		this.annualRevenueGenerated = annualRevenueGenerated;
		this.id = clientId++;
	}

	public double getAnnualRevenueGenerated() {
		return annualRevenueGenerated;
	}

	public void setAnnualRevenueGenerated(double annualRevenueGenerated) {
		this.annualRevenueGenerated = annualRevenueGenerated;
	}

	public int getId() {
		return this.id;
	}

	public List<Experience> getExperiences() {
		return experiences;
	}

	public void setExperiences(List<Experience> experiences) {
		this.experiences = experiences;
	}

	public List<Client> getGroup() {
		return group;
	}

	public void setGroup(List<Client> group) {
		this.group = group;
	}
	
	public double getCommission() {
		return commission;
	}

	public void setCommission(double commission) {
		this.commission = commission;
	}
	
	public List<Award> getAwards() {
		return awards;
	}

	public void setAwards(List<Award> awards) {
		this.awards = awards;
	}

	public void addToGroup(Client c) {
		group.add(c);
	}

	public void removeFromGroup(Client c) {
		group.remove(c);
	}

	// Revenue Generated By Individual
	public double getCalculatedRevenue() {
		return commission * annualRevenueGenerated;
	}

	public String printAwards() {
		if(awards == null || awards.size() == 0) {
			return "Awards:\t\tN/A" + System.lineSeparator();
		}

		String stringToReturn = "Awards:\t\t";
		for(Award award : awards) {
			stringToReturn += award.toString() + " | ";
		}
		
		return stringToReturn + System.lineSeparator();
	}

	public String printExperiences() {
		if(experiences == null || experiences.size() == 0) {
			return "Experiences:\tN/A" + System.lineSeparator();
		}

		String toReturn = "Experiences:\t";
		for(Experience exp : experiences) {
			toReturn += exp.toString() + " | ";
		}

		return toReturn + System.lineSeparator();
	}

	public String printGroupMembers() {
		if(group.size() == 0) {
			return "Clients in group: N/A" + System.lineSeparator();
		}

		String stringToReturn = "Clients in group:" + System.lineSeparator() + System.lineSeparator();
		for(Client client : group) {
			stringToReturn += client.getStringToPrintToConsole() + System.lineSeparator();
		}

		return stringToReturn;
	}

	public String getStringToPrintToConsole() {
		String toReturn = "";
		
		toReturn += "Client ID:\t" + id + System.lineSeparator();
		toReturn += super.getStringToPrintToConsole();
		toReturn += "Commission:\t" + commission + System.lineSeparator();
		toReturn += "Revenue:\t" + annualRevenueGenerated + System.lineSeparator();

		return toReturn;
	}
	
	public abstract String toString();
}